const Menu = [
    {
        id: 1,
        image: `${process.env.PUBLIC_URL}/images/maggi3.jpg`,
        name: "Maggi",
        category: "breakfast",
        price: "12₹",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 2,
        image: `${process.env.PUBLIC_URL}/images/pakoda.jpg`,
        name: "Pakoda",
        category: "evening",
        price: "20₹",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 3,
        image: `${process.env.PUBLIC_URL}/images/corn.jpg`,
        name: "Corn",
        category: "breakfast",
        price: "15₹",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 4,
        image: `${process.env.PUBLIC_URL}/images/chole.jpg`,
        name: "Chole Bhature",
        category: "lunch",
        price: "50₹",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 5,
        image: `${process.env.PUBLIC_URL}/images/pizza2.jpg`,
        name: "Pizza",
        category: "dinner",
        price: "100₹",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 6,
        image: `${process.env.PUBLIC_URL}/images/non-veg-thali.jpg`,
        name: "Non-Veg Thali",
        category: "dinner",
        price: "180₹",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 7,
        image: `${process.env.PUBLIC_URL}/images/sweets.jpg`,
        name: "Sweets",
        category: "dinner",
        price: "60₹",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 8,
        image: `${process.env.PUBLIC_URL}/images/rajma-chawal.jpg`,
        name: "Rajma Chawal",
        category: "lunch",
        price: "80₹",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
        id: 9,
        image: `${process.env.PUBLIC_URL}/images/samosa.jpg`,
        name: "Samosa",
        category: "evening",
        price: "20₹",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
];

export default Menu;
